name: Run WSB Pipeline Daily

on:
  schedule:
    # 20:01 UTC = 4:01 PM EST (adjust if you want another time)
    - cron: "1 20 * * *"
  workflow_dispatch:

permissions:
  contents: write   # ✅ allow pushing commits back to repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true   # ✅ ensures git push works later

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: python pipeline.py

      - name: Commit and push results
        run: |
          git add data/mentions_history.csv
          git commit -m "Daily data update" || echo "No changes to commit"
          git push
