name: Run WSB Pipeline Daily

on:
  schedule:
    # Run Mon–Fri at 21:05 UTC (4:05 PM EST in winter, 5:05 PM EDT in summer)
    - cron: "5 21 * * 1-5"
  workflow_dispatch: {}  # allows manual run from the Actions tab

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: python pipeline.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/mentions_history.csv
          git commit -m "Daily data update" || echo "No changes to commit"
          git push
